apiVersion: extensions/v1beta1
kind: Deployment           
metadata:
  name: eureka-deployment                          
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka                      
    spec:
      containers:                       
      - name: eureka                     
        image: debajyotim/serviceregistry             
        ports:
        - containerPort: 8761           
 
