apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: debajyotim/configserver
        ports:
        - containerPort: 8888
